export function circuitEditor(root,p,save){const e=p.electrical,el=(t,text)=>{const n=document.createElement(t);if(text)n.textContent=text;return n;};const form=el('details');form.append(el('summary','Редактировать группы и каналы'));root.append(form);const select=el('select');select.setAttribute('aria-label','Редактируемая группа');for(const c of e.circuits){const o=el('option',c.id+' · '+c.name);o.value=c.id;select.append(o);}form.append(select);const body=el('div');form.append(body);
 function render(){body.replaceChildren();const c=e.circuits.find(c=>c.id===select.value);if(!c)return;const inputs={};for(const[key,label,type]of [['name','Название','text'],['powerW','Расчётная мощность, Вт','number'],['cable','Кабель группы','text']]){const l=el('label',label),input=el('input');input.type=type;input.value=c[key];l.append(input);body.append(l);inputs[key]=input;}
 const protection=el('select');protection.setAttribute('aria-label','Защита группы');for(const q of e.protections){const o=el('option',q.id+' · '+q.proposal);o.value=q.id;protection.append(o);}protection.value=c.protection;protection.disabled=c.type!=='lighting';body.append(el('label','Защита'),protection);const channel=el('select');channel.setAttribute('aria-label','Канал реле');const empty=el('option','Канал не назначен');empty.value='';channel.append(empty);for(const m of e.modules.filter(m=>m.model.includes('MR6C')))for(let i=1;i<=6;i++){const o=el('option',m.id+'/K'+i);o.value=m.id+'/K'+i;channel.append(o);}channel.value=c.channel||'';if(c.type==='lighting')body.append(el('label','Канал группы света'),channel);
 const apply=el('button','Сохранить группу');apply.onclick=()=>{try{const q=JSON.parse(JSON.stringify(p)),ce=q.electrical.circuits.find(x=>x.id===c.id),power=+inputs.powerW.value;if(!Number.isFinite(power)||power<0)throw Error('Некорректная мощность');ce.name=inputs.name.value;ce.powerW=power;ce.estimatedCurrentA=+((power||0)/230).toFixed(2);ce.cable=inputs.cable.value;if(c.type==='lighting'){
 const ch=channel.value;if(ch&&q.electrical.circuits.some(x=>x.id!==c.id&&x.channel===ch))throw Error('Этот канал уже занят другой группой');const m=q.electrical.modules.find(m=>ch.startsWith(m.id+'/')),qid=protection.value;if(!qid)throw Error('Выберите защиту');if(m?.protection&&m.protection!==qid)throw Error('У этого модуля уже есть защита '+m.protection+'. Выберите её для общей группы питания.');ce.channel=ch||null;ce.protection=qid;const pr=q.electrical.protections.find(x=>x.id===qid);ce.protectionProposal=pr.proposal;if(m)m.protection=qid;
 const n=q.electrical.panelWiring;if(n){n.wires=n.wires.filter(w=>w.circuit!==ce.id);const xt='XT-'+ce.id;if(!n.devices.some(d=>d.id===xt))n.devices.push({id:xt,label:ce.name,kind:'terminal',terminals:['L','N','PE'],source:'Функциональные обозначения'});if(ch){for(const[from,to,signal,color]of [[ch,'L','L switched','#b88050'],['XD-'+qid+'/N','N','N','#53a9ed'],['XPE/PE','PE','PE','#a8c84c']])n.wires.push({id:'EDIT-'+ce.id+'-'+to,from,to:xt+'/'+to,circuit:ce.id,signal,color,sectionMm2:1.5,notes:'Изменено вручную; проверить монтаж',status:'needs_verification'});for(const terminal of ['C1','C2'])if(!n.wires.some(w=>w.to===m.id+'/'+terminal))n.wires.push({id:'EDIT-'+m.id+'-'+terminal,from:'XD-'+qid+'/L',to:m.id+'/'+terminal,circuit:qid,signal:'L',color:'#b88050',sectionMm2:1.5,status:'needs_verification',notes:'Питание общей группы реле; проверить монтаж'});}}
 }else if(protection.value){ce.protection=protection.value;ce.protectionProposal=q.electrical.protections.find(x=>x.id===protection.value).proposal;q.electrical.panelWiring&&(q.electrical.panelWiring.status='needs_verification');}
 for(const r of q.routes.filter(r=>r.circuit===ce.id)){r.cable=ce.cable;r.channel=ce.channel;r.status='needs_verification';const match=ce.cable.match(/×([\d,\.]+)\s*$/);r.sectionMm2=match?+match[1].replace(',','.'):null;}
 for(const pr of q.electrical.protections){pr.circuits=q.electrical.circuits.filter(x=>x.protection===pr.id).map(x=>x.id);if(pr.circuits.length)pr.powerW=q.electrical.circuits.filter(x=>x.protection===pr.id).reduce((s,x)=>s+x.powerW,0);if(pr.powerW/230>pr.amps)throw Error(pr.id+': оценка нагрузки превышает номинал. Проверьте разделение групп.');}ce.status='needs_verification';save(q);
 }catch(err){alert(err.message);}};body.append(apply,el('p','Состав группы меняется добавлением и удалением её ответвлений. Назначение защит предварительное; после правок проверить контактную карту и пусковые токи.'));}select.onchange=render;render();}
