import {clone,validate,recalculateElectrical} from './model.js?v=8.4.0';
export function orthogonal(points,order='xz'){const out=[points[0].slice()];for(const b of points.slice(1)){let a=out.at(-1).slice();for(const i of (order==='zx'?[2,0,1]:[0,2,1])){if(Math.abs(a[i]-b[i])>.00001){a=a.slice();a[i]=b[i];out.push(a);}}}return out;}
export function freshId(p,prefix){const ids=new Set([...p.objects,...p.routes,...p.junctionBoxes,...(p.electrical?.circuits||[])].map(o=>o.id));let n=1;while(ids.has(prefix+n))n++;return prefix+n;}
export function editUI(root,getProject,commit,selectId,routeMode){
 const el=(t,text)=>{const e=document.createElement(t);if(text!==undefined)e.textContent=text;return e;};
 const button=(text,fn)=>{const b=el('button',text);b.onclick=fn;return b;};
 function fields(parent,items){const refs={};for(const[id,label,value,type='text']of items){const l=el('label',label),input=el('input');input.type=type;input.value=value??'';if(type==='number')input.step='any';l.append(input);parent.append(l);refs[id]=input;}return refs;}
 function apply(fn){const p=clone(getProject());try{fn(p);recalculateElectrical(p);validate(p);commit(p);}catch(e){alert(e.message);}}
 function render(record,kind){root.replaceChildren();if(!record)return;
 const title=el('h3','Правка выбранного объекта');root.append(title);
 if(kind==='route'){
  root.append(el('p','Выберите вершину и двигайте её на плане. Концы привязаны к устройствам; промежуточные точки задают обходы.'));
  const f=fields(root,[['name','Кабель',record.cable],['conduit','Гофра / труба',record.conduit],['section','Сечение, мм²',record.sectionMm2||'', 'number']]);
  root.append(button('Сохранить характеристики',()=>apply(p=>{const r=p.routes.find(r=>r.id===record.id);r.cable=f.name.value;r.conduit=f.conduit.value;r.sectionMm2=+f.section.value||null;r.status='needs_verification';})),button('Редактировать путь на плане',()=>routeMode(record.id)),button('Выровнять X/Z',()=>apply(p=>{const r=p.routes.find(r=>r.id===record.id);r.route=orthogonal(r.route);r.manualRoute=true;r.status='needs_verification';})),button('Добавить точку посередине',()=>apply(p=>{const r=p.routes.find(r=>r.id===record.id);let i=1,max=0;for(let j=1;j<r.route.length;j++){const d=Math.hypot(...r.route[j].map((x,k)=>x-r.route[j-1][k]));if(d>max){max=d;i=j;}}r.route.splice(i,0,r.route[i].map((x,k)=>(x+r.route[i-1][k])/2));r.manualRoute=true;})));
  record.route.forEach((point,i)=>{const d=el('details');d.append(el('summary',`Точка ${i+1} · ${point.map(x=>x.toFixed(2)).join(' / ')}`));const f=fields(d,[['x','X',point[0],'number'],['y','Высота',point[1],'number'],['z','Z',point[2],'number']]);if(i>0&&i<record.route.length-1)d.append(button('Применить точку',()=>apply(p=>{const r=p.routes.find(r=>r.id===record.id);r.route[i]=[+f.x.value,+f.y.value,+f.z.value];r.route=orthogonal(r.route);r.manualRoute=true;r.status='needs_verification';})),button('Удалить точку',()=>apply(p=>{const r=p.routes.find(r=>r.id===record.id);r.route.splice(i,1);r.manualRoute=true;})));else d.append(el('p','Конец привязан к устройству. Переместите устройство для изменения.'));root.append(d);});
 }else if(kind==='object'||kind==='box'){
  const f=fields(root,[['name','Название',record.name||record.id],['rotation','Поворот, °',(record.rotation?.[1]||0)*180/Math.PI,'number']]);root.append(button('Применить название / поворот',()=>apply(p=>{const o=[...p.objects,...p.junctionBoxes].find(o=>o.id===record.id);o.name=f.name.value;o.rotation||=[0,0,0];o.rotation[1]=+f.rotation.value*Math.PI/180;o.status='needs_verification';})),button('↶ Повернуть на 90°',()=>apply(p=>{const o=[...p.objects,...p.junctionBoxes].find(o=>o.id===record.id);o.rotation||=[0,0,0];o.rotation[1]+=Math.PI/2;o.status='needs_verification';})));
 }
 }
 const panel=el('details');panel.className='object-catalog';panel.append(el('summary','Добавить объект или кабель'));root.after(panel);
 const catalog=el('select');catalog.setAttribute('aria-label','Тип нового объекта');for(const [kind,name]of [['socket','Розетка'],['switch','Кнопка без фиксации'],['light','Светильник'],['box','Распредкоробка'],['cabinet','Шкаф'],['chair','Стул'],['table','Стол'],['tv','Телевизор'],['boiler','Бойлер']]){const o=el('option',name);o.value=kind;catalog.append(o);}panel.append(catalog,button('Добавить в центр плана',()=>{let id;apply(p=>{const k=catalog.value;id=freshId(p,k==='box'?'JB-USER-':'OBJ-USER-');const o={id,name:catalog.selectedOptions[0].textContent,kind:k,position:[7,k==='light'?3.15:0,4.5],rotation:[0,0,0],scale:[1,1,1],size:k==='socket'||k==='switch'?[.078,.078,.025]:k==='light'?[.09,.035,.09]:k==='chair'?[.45,.85,.45]:k==='table'?[1.2,.75,.8]:k==='tv'?[1.2,.7,.05]:k==='boiler'?[.5,1,.5]:[.6,1.2,.5],layer:k==='socket'?'power':k==='switch'?'smart':k==='light'?'lighting':k==='box'?'boxes':k==='boiler'?'plumbing':'furniture',status:'needs_verification',source:'Добавлено вручную'};if(k==='socket')o.socketCount=1;(k==='box'?p.junctionBoxes:p.objects).push(o);});if(id)selectId(id);}));
 const start=el('select'),end=el('select'),circuit=el('select');start.setAttribute('aria-label','Начало кабеля');end.setAttribute('aria-label','Конец кабеля');circuit.setAttribute('aria-label','Группа кабеля');panel.append(el('h3','Новый кабель'),el('label','Откуда'),start,el('label','Куда'),end,el('label','Группа'),circuit);
 const f=fields(panel,[['cable','Марка кабеля','ВВГнг(А)-LS 3×1,5'],['height','Высота трассы, м',2.92,'number']]);
 panel.append(button('Создать кабель',()=>{let id;apply(p=>{if(start.value===end.value)throw Error('Выберите разные устройства');const c=p.electrical.circuits.find(c=>c.id===circuit.value);if(!c)throw Error('Сначала создайте или выберите группу');if(c.type==='lighting'&&start.value==='PANEL'&&p.routes.some(r=>r.circuit===c.id&&r.from==='PANEL'))throw Error('У группы уже есть кабель из щита. Начните ответвление от её коробки.');const find=id=>[...p.objects,...p.junctionBoxes].find(o=>o.id===id);const a=find(start.value),b=find(end.value);if(!a||!b)throw Error('Выберите начало и конец');if(b.kind==='panel')throw Error('Щит должен быть началом кабеля');if(a.kind!=='panel'&&!p.routes.some(r=>r.circuit===c.id&&r.to===a.id))throw Error('Сначала подведите питание к начальному объекту');if(p.routes.some(r=>r.circuit===c.id&&r.to===b.id))throw Error('К объекту уже подходит кабель этой группы');if(b.circuit&&b.circuit!==c.id)throw Error('Объект уже относится к другой группе');const y=+f.height.value;if(!(y>0&&y<=p.height))throw Error('Высота должна быть внутри помещения');id=freshId(p,'CABLE-USER-');p.routes.push({id,type:c.type,from:a.id,to:b.id,route:orthogonal([a.position,[a.position[0],y,a.position[2]],[b.position[0],y,b.position[2]],b.position]),circuit:c.id,group:c.id,cable:f.cable.value,conduit:'Отдельная труба · уточнить',homeRun:a.kind==='panel',voltageClass:['smart','ftp','sensors'].includes(c.type)?'SELV / data':'230V',status:'needs_verification',manualRoute:true});if(p.objects.includes(b)&&!c.consumers.includes(b.id)){c.consumers.push(b.id);b.circuit=c.id;}});if(id)selectId(id);}));
 const nf=fields(panel,[['groupname','Название новой группы','Новая группа света']]);panel.append(button('Создать группу света',()=>apply(p=>{p.electrical.circuits.push({id:freshId(p,'C-USER-'),name:nf.groupname.value,type:'lighting',consumers:[],powerW:0,cable:'ВВГнг(А)-LS 3×1,5',protection:'UNASSIGNED',protectionProposal:'Выберите защиту и канал в редакторе щита',channel:null,status:'needs_verification',routeLengthM:0,purchaseEstimateM:0,estimatedCurrentA:0});})));
 function refresh(){for(const s of [start,end,circuit])s.replaceChildren();const p=getProject();for(const o of [...p.objects,...p.junctionBoxes])for(const s of [start,end]){const option=el('option',o.id+' · '+(o.name||o.id));option.value=o.id;s.append(option);}start.value='PANEL';for(const c of p.electrical?.circuits||[]){const option=el('option',c.id+' · '+c.name);option.value=c.id;circuit.append(option);}}
 return {render,refresh};
}
