import {circuitEditor} from './circuit-editor.js?v=8.4.0';
import {openPanelDetail} from './panel-detail.js?v=8.8.0';
// Engineering UI uses project data; no inferred electrical connections in the view.
export function electricalUI(root,getProject,onCircuit,onPanel,onChange){
 let filter='',active='';
 const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 const download=(text,name,type)=>{const a=el('a');const u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
 function render(){
  const p=getProject(),e=p.electrical;root.replaceChildren();if(!e){root.append(el('p','В этом JSON нет новой схемы электрики. Экспортируйте свои правки и верните исходную модель во вкладке «Проект».'));return;}
  root.append(el('p','ЭЛЕКТРИКА / WIREN BOARD','eyebrow'),el('h2','Все линии — к щиту'));
  root.append(el('p','Предварительная схема · мощности и аппараты требуют расчётной проверки','electrical-badge'));
  const stats=el('div',undefined,'stats');for(const [n,t] of [[e.circuits.filter(c=>!c.reserve).length,'цепей'],[e.circuits.filter(c=>c.type==='lighting').length,'групп света'],[e.circuits.filter(c=>c.id.startsWith('C-B-')).length,'кнопок']]){const s=el('span');s.append(el('b',n),document.createTextNode(t));stats.append(s);}root.append(stats);
  const actions=el('div',undefined,'twocol');const panel=el('button','Показать щит'),all=el('button','Все трассы');panel.onclick=onPanel;all.onclick=()=>{active='';onCircuit(null);render();};actions.append(panel,all);root.append(actions);if(onChange)circuitEditor(root,p,onChange);
  const closeup=el('button','Монтаж щита · крупный план','primary wide');closeup.onclick=()=>openPanelDetail(p,onPanel,onChange);root.append(closeup);
  const bom=el('details');bom.append(el('summary','Количество автоматов и модулей'));const counts=new Map();for(const item of e.billOfMaterials||[]){counts.set(item.name,(counts.get(item.name)||0)+item.quantity);}for(const[name,count]of counts)bom.append(el('p',count+' × '+name));bom.append(el('p','Вводной аппарат и DC-защита не входят в этот подсчёт: их подбор ещё не завершён.','muted'));root.append(bom);
  const cab=el('details');cab.open=true;cab.append(el('summary','Компоновка щита · '+e.panelLayout.rails.length+' × 24 DIN'));
  const rails=el('div',undefined,'din-cabinet');e.panelLayout.rails.forEach((row,i)=>{const label=el('small',`РЕЙКА ${i+1}`);const rail=el('div',undefined,'din-rail');for(const b of row){const block=el('button',b.id==='RESERVE'?'···':b.id,'din-block '+b.kind);block.style.flex=b.din;block.title=b.name;block.setAttribute('aria-label',b.id+' · '+b.name);block.onclick=()=>{detail.replaceChildren(el('b',b.id),el('p',b.name));const m=e.modules.find(m=>m.id===b.id);if(m)detail.append(el('p',m.purpose),el('p',m.notes));const q=e.protections.find(q=>q.id===b.id);if(q)detail.append(el('p',q.circuits.join(' · ')||'Внутренняя цепь / резерв'),el('p',q.phase));};rail.append(block);}rails.append(label,rail);});cab.append(rails);const detail=el('div','Нажмите аппарат: назначение, защита и ограничения. Размеры и клеммы условные.','callout');cab.append(detail);root.append(cab);
  const equipment=el('details');equipment.append(el('summary','Оборудование списком'));for(const m of e.modules){const b=el('button',m.id+' · '+m.model,'wide');b.onclick=()=>{equipmentInfo.replaceChildren(el('b',m.purpose),el('p',m.notes));};equipment.append(b);}const equipmentInfo=el('div',undefined,'callout');equipment.append(equipmentInfo);root.append(equipment);
  const bus=el('details');bus.append(el('summary','Шина и работа без контроллера'),el('p',e.bus.devices.join(' → '),'bus-chain'),el('p',e.bus.termination,'muted'),el('p','Кнопки подключены к входам релейных модулей. Локальную матрицу необходимо настроить; межмодульные сцены выполняет контроллер. Защита от протечек — автономная логика MWAC.','muted'));root.append(bus);
  const label=el('label','Цепь / помещение / потребитель');label.htmlFor='circuit-search';const search=el('input');search.id='circuit-search';search.type='search';search.placeholder='Например: кухня, SW-03, C-L01';search.value=filter;root.append(label,search);
  const list=el('div',undefined,'circuit-list');root.append(list);
  function listRender(){list.replaceChildren();for(const c of e.circuits.filter(c=>JSON.stringify(c).toLowerCase().includes(filter.toLowerCase()))){const b=el('button',undefined,'circuit-item'+(active===c.id?' active':''));b.style.setProperty('--wire',({power:'#f27858',lighting:'#f6d883',smart:'#57d5ba',ftp:'#4eaaff',curtains:'#ba9afa',sensors:'#50d3df',hvac:'#edb75e'})[c.type]);b.append(el('b',c.id+' · '+c.name),el('small',(c.reserve?'Резерв · ':c.powerW?c.powerW+' Вт ≈ · ':'')+c.routeLengthM+' м · '+(c.channel||c.protection)));b.onclick=()=>{active=c.id;onCircuit(c);listRender();showCircuit(c);};list.append(b);}}
  search.oninput=()=>{filter=search.value;listRender();};listRender();const card=el('div',undefined,'callout');card.hidden=true;root.insertBefore(card,list);
  function showCircuit(c){card.hidden=false;card.replaceChildren(el('b',c.id+' · '+c.name));for(const t of [c.cable,c.protection+' · '+c.protectionProposal,c.channel?'Канал: '+c.channel:'Постоянное питание; не коммутируется WB',c.estimatedCurrentA!==null?'Оценка тока: '+c.estimatedCurrentA+' А при 230 В':'Сигнальная / низковольтная цепь','Потребители: '+c.consumers.join(', '),'Трасса: '+c.routeLengthM+' м; оценка с запасом: '+c.purchaseEstimateM+' м',c.notes,c.groupingBasis])if(t)card.append(el('p',t));const linked=p.objects.filter(o=>o.controls?.includes(c.id));if(linked.length)card.append(el('p','Кнопки: '+linked.map(o=>o.id+' → '+o.inputChannel).join('; ')));}
  if(active){const c=e.circuits.find(c=>c.id===active);if(c)showCircuit(c);}
  const csv=el('button','Скачать кабельный журнал CSV','wide');csv.onclick=()=>{const quote=x=>'"'+String(x??'').replaceAll('"','""')+'"';const rows=[['ID','Тип','От','До','Группа','Кабель','Труба','Длина м','Канал','Статус'],...p.routes.map(r=>[r.id,r.type,r.from,r.to,r.circuit,r.cable,r.conduit,r.lengthM,r.channel,r.status])];download('\ufeff'+rows.map(r=>r.map(quote).join(';')).join('\r\n'),'vydrino-cables-8.3.csv','text/csv;charset=utf-8');};root.append(csv);
  const notes=el('details');notes.append(el('summary','Допущения и нормативная основа'));for(const n of e.notes)notes.append(el('p',n,'muted'));for(const s of e.sources){try{const u=new URL(s.url);if(u.protocol!=='https:')continue;const a=el('a',s.title);a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';notes.append(a);}catch{}}root.append(notes);
 }
 return {render};
}
