export const clone=x=>JSON.parse(JSON.stringify(x));
export function wallFrame(project,wall){const a=project.nodes.find(n=>n.id===wall.a).position,b=project.nodes.find(n=>n.id===wall.b).position;const dx=b[0]-a[0],dz=b[1]-a[1],length=Math.hypot(dx,dz);return {a,b,dx:dx/length,dz:dz/length,length};}
export function openingPosition(p,o){const w=p.walls.find(w=>w.id===o.wallId),f=wallFrame(p,w);return [f.a[0]+f.dx*(o.offset+o.width/2),o.sillHeight,f.a[1]+f.dz*(o.offset+o.width/2)];}
export function validate(p){
 if(!p||p.schemaVersion!==8||p.projectId!=='vydrino-house'||p.units!=='m')throw Error('Нужен JSON проекта Выдрино версии 8.');
 const all=new Set(),finite=(a,n)=>Array.isArray(a)&&a.length===n&&a.every(v=>Number.isFinite(v)&&Math.abs(v)<1000);
 for(const k of ['nodes','walls','openings','objects','junctionBoxes','routes','rooms','sources','floorPolygon','heatingZones','verification'])if(!Array.isArray(p[k]))throw Error('Нет раздела '+k);
 for(const k of ['nodes','walls','openings','objects','junctionBoxes','routes','rooms','sources','heatingZones']){
 if(p[k].length>3000)throw Error('Слишком много элементов');
 for(const o of p[k]){if(typeof o.id!=='string'||all.has(o.id))throw Error('Повторяющийся или пустой ID');all.add(o.id);}}
 for(const n of p.nodes)if(!finite(n.position,2))throw Error('Некорректные координаты узла');
 for(const w of p.walls){if(!p.nodes.some(n=>n.id===w.a)||!p.nodes.some(n=>n.id===w.b))throw Error('Не найден узел стены');if(!(w.thickness>.01&&w.thickness<2&&w.height>.1&&w.height<10&&wallFrame(p,w).length>.03))throw Error('Некорректные размеры стены');}
 for(const o of p.openings){const w=p.walls.find(w=>w.id===o.wallId);if(!w||!['window','door'].includes(o.type)||!Number.isFinite(o.offset)||o.offset<0||!(o.width>.05)||!(o.height>.05)||!(o.sillHeight>=0)||o.sillHeight+o.height>w.height+.001||o.offset+o.width>wallFrame(p,w).length+.005)throw Error('Проём '+o.id+' выходит за стену');}
 for(const w of p.walls){let end=-1;for(const o of p.openings.filter(o=>o.wallId===w.id).sort((a,b)=>a.offset-b.offset)){if(o.offset<end-.001)throw Error('Проёмы пересекаются');end=o.offset+o.width;}}
 for(const o of [...p.objects,...p.junctionBoxes]){if(!finite(o.position,3))throw Error('Некорректный объект');if(o.size&&(!finite(o.size,3)||o.size.some(v=>v<=0||v>30)))throw Error('Некорректный размер');if(o.rotation&&!finite(o.rotation,3))throw Error('Некорректный поворот');if(o.scale&&(!finite(o.scale,3)||o.scale.some(v=>v<=0||v>20)))throw Error('Некорректный масштаб');}
 for(const s of p.sources)if(typeof s.image!=='string'||!/^assets\/blueprint-(?:[0-6]|smart)\.webp$/.test(s.image)||!finite(s.origin,2)||!finite(s.size,2)||s.size.some(v=>v<=0))throw Error('Некорректный чертёж');
 for(const r of p.routes)if(!Array.isArray(r.route)||r.route.length>100||r.route.some(a=>!finite(a,3))||!all.has(r.from)||!all.has(r.to))throw Error('Некорректная трасса');
 for(const r of [...p.rooms,...p.heatingZones,{polygon:p.floorPolygon}])if(!Array.isArray(r.polygon)||r.polygon.length<3||r.polygon.length>2000||r.polygon.some(a=>!finite(a,2)))throw Error('Некорректный контур');
 if(p.electrical){const e=p.electrical;if(!Array.isArray(e.circuits)||!Array.isArray(e.modules)||!Array.isArray(e.protections)||!Array.isArray(e.notes)||!Array.isArray(e.sources)||!Array.isArray(e.bus?.devices)||!Array.isArray(e.panelLayout?.rails)||(e.panelLayout.rails.length<1||e.panelLayout.rails.length>16))throw Error('Некорректный раздел электрики');
 const ids=new Set();for(const c of e.circuits){if(ids.has(c.id)||typeof c.id!=='string'||!Array.isArray(c.consumers)||c.consumers.some(id=>!p.objects.some(o=>o.id===id))||!Number.isFinite(c.powerW)||c.powerW<0||typeof c.cable!=='string')throw Error('Некорректная цепь');ids.add(c.id);}
 for(const r of p.routes)if(!ids.has(r.circuit))throw Error('Трасса без цепи');
 if(e.panelWiring){const n=e.panelWiring;if(!Array.isArray(n.devices)||!Array.isArray(n.wires)||!Array.isArray(n.notes)||n.devices.length>1000||n.wires.length>5000)throw Error('Некорректная карта щита');const terms=new Set(),devices=new Set(),wires=new Set();for(const d of n.devices){if(typeof d.id!=='string'||devices.has(d.id)||!Array.isArray(d.terminals)||d.terminals.some(t=>typeof t!=='string')||typeof d.source!=='string')throw Error('Некорректные клеммы');devices.add(d.id);for(const t of d.terminals)terms.add(d.id+'/'+t);}for(const w of n.wires){if(typeof w.id!=='string'||wires.has(w.id)||!terms.has(w.from)||!terms.has(w.to)||typeof w.signal!=='string'||typeof w.color!=='string'||(w.sectionMm2!==null&&!(Number.isFinite(w.sectionMm2)&&w.sectionMm2>0)))throw Error('Некорректное соединение щита');wires.add(w.id);}}
 for(const row of e.panelLayout.rails)if(!Array.isArray(row)||row.some(b=>!Number.isFinite(b.din)||b.din<=0)||row.reduce((a,b)=>a+b.din,0)>24)throw Error('Переполнение DIN-рейки');
 }
 return true;
}
export function recalculateElectrical(p){if(!p.electrical)return;for(const r of p.routes)r.lengthM=+r.route.slice(1).reduce((n,q,i)=>n+Math.hypot(...q.map((x,j)=>x-r.route[i][j])),0).toFixed(2);for(const c of p.electrical.circuits){const routes=p.routes.filter(r=>r.circuit===c.id);c.routeLengthM=+routes.reduce((s,r)=>s+r.lengthM,0).toFixed(2);c.purchaseEstimateM=Math.ceil(c.routeLengthM*1.15+routes.filter(r=>r.homeRun).length*2);}}
export function reroute(p,id){for(const r of p.routes){if(r.from!==id&&r.to!==id)continue;const objects=[...p.objects,...p.junctionBoxes],from=objects.find(o=>o.id===r.from),to=objects.find(o=>o.id===r.to);if(!from||!to)continue;let a=from.position.slice(),b=to.position.slice();if(r.manualRoute){r.route[0]=a;r.route[r.route.length-1]=b;r.status='needs_verification';continue;}const h=r.voltageClass==='SELV / data'?3.08:2.92;if(from.kind==='panel')a=[a[0]+.17,a[1]+from.size[1],a[2]];const lane=r.homeRun&&r.route.length>3?r.route[2][2]:a[2];r.route=[a,[a[0],h,a[2]],[a[0],h,lane],[b[0],h,lane],[b[0],h,b[2]],b].filter((q,i,arr)=>!i||Math.hypot(...q.map((v,j)=>v-arr[i-1][j]))>.001);r.status='needs_verification';}recalculateElectrical(p);}
export function removeObject(p,id){p.objects=p.objects.filter(o=>o.id!==id);p.junctionBoxes=p.junctionBoxes.filter(o=>o.id!==id);p.routes=p.routes.filter(o=>o.id!==id&&o.from!==id&&o.to!==id);if(p.electrical){for(const c of p.electrical.circuits){if(c.consumers.includes(id)){c.consumers=c.consumers.filter(x=>x!==id);c.status='needs_verification';c.notes='Потребитель удалён вручную. Проверить цепь и карту каналов.';}}p.electrical.notes=Array.from(new Set([...p.electrical.notes,'Объекты или трассы удалены вручную: проверить полноту соединений и защит.']));}recalculateElectrical(p);}
export class History{constructor(p){this.entries=[clone(p)];this.index=0;}push(p){const s=clone(p);if(JSON.stringify(s)===JSON.stringify(this.entries[this.index]))return;this.entries.splice(++this.index);this.entries.push(s);if(this.entries.length>60){this.entries.shift();this.index--;}}undo(){if(this.index>0)return clone(this.entries[--this.index]);}redo(){if(this.index<this.entries.length-1)return clone(this.entries[++this.index]);}}
