import {panelLayoutView} from './panel-layout-view.js?v=8.8.0';
import {panelEditor} from './panel-editor.js?v=8.4.0';
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const svgEl=(tag,attrs={},text)=>{const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e;};
export function openPanelDetail(p,on3D,onChange){
 const e=p.electrical,n=e.panelWiring,dialog=el('dialog',undefined,'panel-dialog');
 const header=el('header');const title=el('div');title.append(el('small','ЩР-01 / ТЕХКОМНАТА'),el('h2','Щит крупным планом'));const close=el('button','Закрыть ×');close.onclick=()=>dialog.close();header.append(title,close);dialog.append(header);
 const intro=el('p','Предварительная компоновка. Контакты WB подписаны по документации; расположение клемм условное. Ввод и окончательные номиналы требуют расчёта.','callout');dialog.append(intro);if(onChange)panelEditor(dialog,p,q=>{onChange(q);dialog.close();openPanelDetail(q,on3D,onChange);});
 const bar=el('div',undefined,'panel-toolbar');const select=el('select');select.setAttribute('aria-label','Цепь в щите');for(const c of e.circuits.filter(c=>!c.reserve)){const o=el('option',c.id+' · '+c.name);o.value=c.id;select.append(o);}for(const [id,name]of [['INTERNAL','Питание модулей 24 В'],['RS485','Шина RS-485']]){const o=el('option',name);o.value=id;select.append(o);}const toggle=el('button','Показать соединения');const focus=el('button','Щит в модели');focus.onclick=()=>{dialog.close();on3D();};bar.append(select,toggle,focus);dialog.append(bar);
 const scroll=el('div',undefined,'panel-scroll'),info=el('div',undefined,'panel-terminal-info');dialog.append(scroll,info);let connections=false;
 function showDevice(id){const d=n?.devices.find(d=>d.id===id);info.replaceChildren(el('h3',id));if(d){info.append(el('p',d.label),el('p','Контакты: '+d.terminals.join(' · ')));if(d.source.startsWith('https:')){const a=el('a','Документация производителя');a.href=d.source;a.target='_blank';a.rel='noopener';info.append(a);}else info.append(el('p',d.source,'muted'));}const related=n?.wires.filter(w=>w.from.startsWith(id+'/')||w.to.startsWith(id+'/'))||[];table(related);}
 function table(wires){const t=el('table');const head=el('tr');for(const s of ['Провод','От → До','Жила','Цепь'])head.append(el('th',s));t.append(head);for(const w of wires){const tr=el('tr');for(const s of [w.id,w.from+' → '+w.to,(w.sectionMm2??'по кабелю')+(w.sectionMm2?' мм²':'')+' · '+w.signal,w.circuit])tr.append(el('td',s));tr.title=w.notes;t.append(tr);}const wrapper=el('div',undefined,'table-scroll');wrapper.append(t);info.append(wrapper);}
 function render(){scroll.replaceChildren();info.replaceChildren();toggle.textContent=connections?'Компоновка по рейкам':'Показать соединения';if(!connections){
  scroll.append(panelLayoutView(e,showDevice));info.append(el('p','Нажмите аппарат для просмотра контактов и подключений. Компоновка сохраняет редактирование DIN-реек. Клеммы показаны условно: количество и модель подбираются по кабельному журналу.'));
 }else{
  if(!n){info.append(el('p','В импортированном JSON нет карты соединений.'));return;}
  const c=e.circuits.find(c=>c.id===select.value);const wires=n.wires.filter(w=>w.circuit===select.value||(c&&w.circuit===c.protection));const ids=[...new Set(wires.flatMap(w=>[w.from.split('/')[0],w.to.split('/')[0]]))];const nodes=ids.map(id=>n.devices.find(d=>d.id===id)).filter(Boolean);const cols=nodes.length>8?3:2;const positions=new Map();const height=Math.max(550,Math.ceil(nodes.length/cols)*250+80);const svg=svgEl('svg',{viewBox:`0 0 1100 ${height}`,role:'img','aria-label':'Контактная карта выбранной цепи'});svg.append(svgEl('rect',{width:1100,height,fill:'#15232d',rx:18}));const points=new Map();
  nodes.forEach((d,i)=>{const x=70+(i%cols)*(960/cols),y=60+Math.floor(i/cols)*250;positions.set(d.id,{x,y});const terms=d.terminals.filter(t=>wires.some(w=>w.from===d.id+'/'+t||w.to===d.id+'/'+t));terms.forEach((t,j)=>points.set(d.id+'/'+t,{x:x+240,left:x,y:y+55+j*19}));});
  wires.forEach((w,i)=>{const a=points.get(w.from),b=points.get(w.to);if(!a||!b)return;const same=a.left===b.left,ax=same||a.left<b.left?a.x:a.left,bx=same||b.left<a.left?b.x:b.left;const lane=same?a.x+24+(i%8)*5:(ax+bx)/2+(i%8-4)*5;const path=svgEl('path',{d:`M ${ax} ${a.y} H ${lane} V ${b.y} H ${bx}`,fill:'none',stroke:w.color,'stroke-width':2.4,'stroke-linejoin':'round',opacity:.8});path.append(svgEl('title',{},`${w.id}: ${w.from} → ${w.to}`));svg.append(path);});
  nodes.forEach(d=>{const {x,y}=positions.get(d.id);const terms=d.terminals.filter(t=>points.has(d.id+'/'+t));const g=svgEl('g',{role:'button',tabindex:0,'aria-label':d.id,style:'cursor:pointer'});g.append(svgEl('rect',{x,y,width:240,height:Math.max(110,terms.length*19+65),rx:8,fill:d.kind==='module'?'#386e60':'#273e49',stroke:'#6a8b94'}),svgEl('text',{x:x+12,y:y+25,fill:'#f0f5ee','font-size':17},d.id));terms.forEach(t=>{const point=points.get(d.id+'/'+t);g.append(svgEl('text',{x:x+12,y:point.y+5,fill:'#cce0df','font-size':14},t),svgEl('circle',{cx:point.x,cy:point.y,r:4,fill:'#d7e7de'}),svgEl('circle',{cx:point.left,cy:point.y,r:4,fill:'#d7e7de'}));});g.onclick=()=>showDevice(d.id);g.onkeydown=ev=>{if(ev.key==='Enter')showDevice(d.id);};svg.append(g);});scroll.append(svg);info.append(el('h3',c?c.name:select.selectedOptions[0].textContent),el('p','Каналы на рисунке схематические. Таблица ниже определяет соединения; запас длины внутри щита не включён в длину квартирных трасс.','muted'));table(wires);
 }
 }
 select.onchange=()=>{connections=true;render();};toggle.onclick=()=>{connections=!connections;render();};
 const notes=el('details');notes.append(el('summary','Что уточнить перед монтажом'));for(const note of n?.notes||[])notes.append(el('p',note));dialog.append(notes);document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();render();
}
