const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const svgEl=(tag,attrs={},text)=>{const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e;};
export function openPanelDetail(p,on3D){
 const e=p.electrical,n=e.panelWiring,dialog=el('dialog',undefined,'panel-dialog');
 const header=el('header');const title=el('div');title.append(el('small','ЩР-01 / ТЕХКОМНАТА'),el('h2','Щит крупным планом'));const close=el('button','Закрыть ×');close.onclick=()=>dialog.close();header.append(title,close);dialog.append(header);
 const intro=el('p','Предварительная компоновка. Контакты WB подписаны по документации; расположение клемм условное. Ввод и окончательные номиналы требуют расчёта.','callout');dialog.append(intro);
 const bar=el('div',undefined,'panel-toolbar');const select=el('select');select.setAttribute('aria-label','Цепь в щите');for(const c of e.circuits.filter(c=>!c.reserve)){const o=el('option',c.id+' · '+c.name);o.value=c.id;select.append(o);}for(const [id,name]of [['INTERNAL','Питание модулей 24 В'],['RS485','Шина RS-485']]){const o=el('option',name);o.value=id;select.append(o);}const toggle=el('button','Показать соединения');const focus=el('button','Щит в 3D');focus.onclick=()=>{dialog.close();on3D();};bar.append(select,toggle,focus);dialog.append(bar);
 const scroll=el('div',undefined,'panel-scroll'),info=el('div',undefined,'panel-terminal-info');dialog.append(scroll,info);let connections=false;
 function showDevice(id){const d=n?.devices.find(d=>d.id===id);info.replaceChildren(el('h3',id));if(d){info.append(el('p',d.label),el('p','Контакты: '+d.terminals.join(' · ')));if(d.source.startsWith('https:')){const a=el('a','Документация производителя');a.href=d.source;a.target='_blank';a.rel='noopener';info.append(a);}else info.append(el('p',d.source,'muted'));}const related=n?.wires.filter(w=>w.from.startsWith(id+'/')||w.to.startsWith(id+'/'))||[];table(related);}
 function table(wires){const t=el('table');const head=el('tr');for(const s of ['Провод','От → До','Жила','Цепь'])head.append(el('th',s));t.append(head);for(const w of wires){const tr=el('tr');for(const s of [w.id,w.from+' → '+w.to,(w.sectionMm2??'по кабелю')+(w.sectionMm2?' мм²':'')+' · '+w.signal,w.circuit])tr.append(el('td',s));tr.title=w.notes;t.append(tr);}const wrapper=el('div',undefined,'table-scroll');wrapper.append(t);info.append(wrapper);}
 function render(){scroll.replaceChildren();info.replaceChildren();toggle.textContent=connections?'Компоновка по рейкам':'Показать соединения';if(!connections){
  const svg=svgEl('svg',{viewBox:'0 0 1100 1510',role:'img','aria-label':'Девять DIN-реек с автоматами и модулями'});svg.append(svgEl('rect',{x:12,y:12,width:1076,height:1480,rx:22,fill:'#1a2932',stroke:'#566c77','stroke-width':3}));
  for(const x of [30,1038])svg.append(svgEl('rect',{x,y:48,width:30,height:1400,fill:'#50616a',rx:4}));
  e.panelLayout.rails.forEach((row,i)=>{const y=60+i*156;svg.append(svgEl('text',{x:76,y:y-12,fill:'#a4bbc7','font-size':13},'РЕЙКА '+(i+1)));svg.append(svgEl('rect',{x:75,y:y+105,width:946,height:27,fill:'#526771',rx:3}));let x=75;for(const item of row){const w=item.din*39.4;const g=svgEl('g',{tabindex:0,role:'button','aria-label':item.id+' '+item.name,style:'cursor:pointer'});g.append(svgEl('rect',{x,y,width:w-4,height:94,rx:4,fill:item.kind==='module'?'#68a694':item.kind==='reserve'?'#293c47':'#e2e7e3',stroke:'#839892'}));if(item.kind!=='reserve'){for(const yy of [y+5,y+78]){for(let j=0;j<Math.min(12,item.din*2);j++){const xx=x+8+j*(w-20)/Math.max(1,Math.min(12,item.din*2)-1);g.append(svgEl('rect',{x:xx,y:yy,width:7,height:10,fill:'#385954'}),svgEl('circle',{cx:xx+3.5,cy:yy+5,r:2,fill:'#c1d1cc'}));}}g.append(svgEl('text',{x:x+w/2-2,y:y+37,'text-anchor':'middle',fill:'#163029','font-size':Math.min(15,w/6.5)},item.id));if(item.kind==='protection'){const q=e.protections.find(q=>q.id===item.id);g.append(svgEl('rect',{x:x+w*.32,y:y+48,width:w*.36,height:18,rx:3,fill:'#273b45'}));if(q)g.append(svgEl('text',{x:x+w/2,y:y+74,'text-anchor':'middle',fill:'#17332f','font-size':12},q.curve+q.amps+' / A'));}else if(item.kind==='module')g.append(svgEl('text',{x:x+w/2,y:y+60,'text-anchor':'middle',fill:'#143b30','font-size':Math.min(12,w/11)},item.name));}else g.append(svgEl('text',{x:x+w/2,y:y+52,'text-anchor':'middle',fill:'#809ba9','font-size':14},item.id==='INPUT'?'ВВОД · ПОДБОР':'РЕЗЕРВ'));g.onclick=()=>showDevice(item.id);g.onkeydown=ev=>{if(ev.key==='Enter')showDevice(item.id);};svg.append(g);x+=w;}});scroll.append(svg);info.append(el('p','Нажмите аппарат, чтобы увидеть его контакты и таблицу подключений. Разделение силовых и сигнальных клемм показано в двух нижних рядах.'));
 }else{
  if(!n){info.append(el('p','В импортированном JSON нет карты соединений.'));return;}
  const c=e.circuits.find(c=>c.id===select.value);const wires=n.wires.filter(w=>w.circuit===select.value||(c&&w.circuit===c.protection));const ids=[...new Set(wires.flatMap(w=>[w.from.split('/')[0],w.to.split('/')[0]]))];const nodes=ids.map(id=>n.devices.find(d=>d.id===id)).filter(Boolean);const cols=nodes.length>8?3:2;const positions=new Map();const height=Math.max(550,Math.ceil(nodes.length/cols)*250+80);const svg=svgEl('svg',{viewBox:`0 0 1100 ${height}`,role:'img','aria-label':'Контактная карта выбранной цепи'});svg.append(svgEl('rect',{width:1100,height,fill:'#15232d',rx:18}));const points=new Map();
  nodes.forEach((d,i)=>{const x=70+(i%cols)*(960/cols),y=60+Math.floor(i/cols)*250;positions.set(d.id,{x,y});const terms=d.terminals.filter(t=>wires.some(w=>w.from===d.id+'/'+t||w.to===d.id+'/'+t));terms.forEach((t,j)=>points.set(d.id+'/'+t,{x:x+240,y:y+55+j*19}));});
  wires.forEach((w,i)=>{const a=points.get(w.from),b=points.get(w.to);if(!a||!b)return;const lane=Math.min(1070,Math.max(a.x,b.x)+24+(i%8)*6);const path=svgEl('path',{d:`M ${a.x} ${a.y} H ${lane} V ${b.y} H ${b.x}`,fill:'none',stroke:w.color,'stroke-width':2.4,'stroke-linejoin':'round',opacity:.8});path.append(svgEl('title',{},`${w.id}: ${w.from} → ${w.to}`));svg.append(path);});
  nodes.forEach(d=>{const {x,y}=positions.get(d.id);const terms=d.terminals.filter(t=>points.has(d.id+'/'+t));const g=svgEl('g',{role:'button',tabindex:0,'aria-label':d.id,style:'cursor:pointer'});g.append(svgEl('rect',{x,y,width:240,height:Math.max(110,terms.length*19+65),rx:8,fill:d.kind==='module'?'#386e60':'#273e49',stroke:'#6a8b94'}),svgEl('text',{x:x+12,y:y+25,fill:'#f0f5ee','font-size':17},d.id));terms.forEach(t=>{const point=points.get(d.id+'/'+t);g.append(svgEl('text',{x:x+12,y:point.y+5,fill:'#cce0df','font-size':14},t),svgEl('circle',{cx:point.x,cy:point.y,r:4,fill:'#d7e7de'}));});g.onclick=()=>showDevice(d.id);g.onkeydown=ev=>{if(ev.key==='Enter')showDevice(d.id);};svg.append(g);});scroll.append(svg);info.append(el('h3',c?c.name:select.selectedOptions[0].textContent),el('p','Каналы на рисунке схематические. Таблица ниже определяет соединения; запас длины внутри щита не включён в длину квартирных трасс.','muted'));table(wires);
 }
 }
 select.onchange=()=>{connections=true;render();};toggle.onclick=()=>{connections=!connections;render();};
 const notes=el('details');notes.append(el('summary','Что уточнить перед монтажом'));for(const note of n?.notes||[])notes.append(el('p',note));dialog.append(notes);document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();render();
}
