import * as THREE from 'three';
import {nightLighting} from './night-lighting.js?v=8.5.1';
export function simulationView(scene,objects,getProject){const group=new THREE.Group();group.name='Home preview';scene.add(group);let active=false;
 const night=nightLighting(scene,objects,getProject);
 function clear(){for(const o of [...group.children]){o.geometry?.dispose();o.material?.dispose();group.remove(o);}}
 function apply(s){if(!active)return;clear();scene.updateMatrixWorld(true);night.apply(s);const p=getProject();
  for(const c of p.electrical?.circuits.filter(c=>c.type==='lighting')||[]){const on=!!s.lights[c.id];for(const id of c.consumers){const g=objects.get(id),o=p.objects.find(o=>o.id===id);if(!g||!o)continue;const last=g.children.filter(m=>m.isMesh).at(-1);if(last?.material){if(!last.userData.simMaterial){last.material=last.material.clone();last.userData.simOriginal={color:last.material.color?.getHex(),emissive:last.material.emissive?.getHex(),intensity:last.material.emissiveIntensity};last.userData.simMaterial=true;last.userData.ownMaterial=true;}last.material.emissive?.set(on?'#ffd98a':'#000000');last.material.emissiveIntensity=on?1.4:0;last.material.color?.set(on?'#fff0c4':'#74828a');}}}
  for(const o of p.objects.filter(o=>o.kind==='curtain')){const g=objects.get(o.id);if(!g)continue;const close=1-(s.curtains[o.id]??100)/100;for(const sign of [-1,1]){const width=o.size[0]*(.07+.43*close),mesh=new THREE.Mesh(new THREE.BoxGeometry(width,2.55,.035),new THREE.MeshStandardMaterial({color:'#cbc5b4',roughness:1,transparent:true,opacity:.88}));mesh.position.set(sign*(o.size[0]/2-width/2),-1.28,0);mesh.applyMatrix4(g.matrixWorld);group.add(mesh);}}
  for(const o of p.objects.filter(o=>/^DP\d+$/.test(o.id)||/^VALVE-/.test(o.id))){const alarm=o.id.startsWith('DP')?!!s.leaks[o.id]:s.waterClosed;const mesh=new THREE.Mesh(new THREE.CircleGeometry(o.id.startsWith('DP')?.16:.12,20),new THREE.MeshBasicMaterial({color:alarm?'#ff645e':'#58cebd',transparent:true,opacity:.9,depthTest:false}));mesh.rotation.x=-Math.PI/2;mesh.position.set(o.position[0],.07,o.position[2]);mesh.renderOrder=250;group.add(mesh);}
 }
 return {apply,setActive(value){night.setActive(value);active=value;group.visible=value;if(!value){clear();for(const o of objects.values())o.traverse(m=>{if(m.userData.simMaterial){m.material.emissive?.set(m.userData.simOriginal.emissive??0);m.material.color?.set(m.userData.simOriginal.color??0xffffff);m.material.emissiveIntensity=m.userData.simOriginal.intensity??0;}});}}};
}
