import * as THREE from 'three';
import {nightLighting} from './night-lighting.js?v=8.6.0';
export function simulationView(scene,objects,getProject){const group=new THREE.Group();group.name='Home preview';scene.add(group);let active=false;
 const night=nightLighting(scene,objects,getProject);const curtainValues=new Map();let curtainTargets={},curtainParts=[];
 function tick(dt){if(!active)return;for(const part of [...new Map(curtainParts.map(p=>[p.id,p])).values()]){const target=curtainTargets[part.id]??100,current=curtainValues.get(part.id)??100;const value=current+Math.sign(target-current)*Math.min(Math.abs(target-current),Math.max(0,Math.min(dt,.1))*45);curtainValues.set(part.id,value);}for(const part of curtainParts){const value=curtainValues.get(part.id)??100,width=part.width*(.07+.43*(1-value/100));part.mesh.scale.x=width;part.mesh.position.copy(part.parent.localToWorld(new THREE.Vector3(part.sign*(part.width/2-width/2),-1.28,0)));part.mesh.quaternion.copy(part.parent.getWorldQuaternion(new THREE.Quaternion()));}}

 function clear(){for(const o of [...group.children]){o.geometry?.dispose();o.material?.dispose();group.remove(o);}}
 function apply(s){if(!active)return;clear();curtainParts=[];curtainTargets=s.curtains;scene.updateMatrixWorld(true);night.apply(s);const p=getProject();
  for(const c of p.electrical?.circuits.filter(c=>c.type==='lighting')||[]){const on=!!s.lights[c.id];for(const id of c.consumers){const g=objects.get(id),o=p.objects.find(o=>o.id===id);if(!g||!o)continue;const emitters=g.children.filter(m=>m.userData.fixtureEmitter);if(!emitters.length)emitters.push(g.children.filter(m=>m.isMesh).at(-1));for(const last of emitters){if(last?.material){if(!last.userData.simMaterial){last.material=last.material.clone();last.userData.simOriginal={color:last.material.color?.getHex(),emissive:last.material.emissive?.getHex(),intensity:last.material.emissiveIntensity};last.userData.simMaterial=true;last.userData.ownMaterial=true;}last.material.emissive?.set(on?'#ffd98a':'#000000');last.material.emissiveIntensity=on?1.4:0;last.material.color?.set(on?'#fff0c4':'#74828a');}}}}
  for(const o of p.objects.filter(o=>o.kind==='curtain')){const g=objects.get(o.id);if(!g)continue;for(const sign of [-1,1]){const geo=new THREE.PlaneGeometry(1,2.55,32,1);const a=geo.attributes.position;for(let i=0;i<a.count;i++)a.setZ(i,Math.cos(a.getX(i)*Math.PI*32)*.027);geo.computeVertexNormals();const mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:'#cbc5b4',roughness:1,side:THREE.DoubleSide}));group.add(mesh);curtainParts.push({id:o.id,parent:g,mesh,sign,width:o.size[0]});}}
  for(const o of p.objects.filter(o=>/^DP\d+$/.test(o.id)||/^VALVE-/.test(o.id))){const alarm=o.id.startsWith('DP')?!!s.leaks[o.id]:s.waterClosed;const mesh=new THREE.Mesh(new THREE.CircleGeometry(o.id.startsWith('DP')?.16:.12,20),new THREE.MeshBasicMaterial({color:alarm?'#ff645e':'#58cebd',transparent:true,opacity:.9,depthTest:false}));mesh.rotation.x=-Math.PI/2;mesh.position.set(o.position[0],.07,o.position[2]);mesh.renderOrder=250;group.add(mesh);}
 }
 return {apply,tick,setActive(value){night.setActive(value);active=value;group.visible=value;if(!value){clear();curtainParts=[];for(const o of objects.values())o.traverse(m=>{if(m.userData.simMaterial){m.material.emissive?.set(m.userData.simOriginal.emissive??0);m.material.color?.set(m.userData.simOriginal.color??0xffffff);m.material.emissiveIntensity=m.userData.simOriginal.intensity??0;}});}}};
}
