import {electricalUI} from './electrical-ui.js?v=8.2.1';
import {createPlanRenderer} from './plan-renderer.js?v=8.2.1';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {clone,wallFrame,openingPosition,validate,reroute,removeObject,History} from './model.js?v=8.2.1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const host=$('#view'),scene=new THREE.Scene();scene.background=new THREE.Color('#111b24');
let renderer,fallback=false;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});}catch(e){fallback=true;renderer=createPlanRenderer();}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(host.clientWidth,host.clientHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;host.prepend(renderer.domElement);
const perspective=new THREE.PerspectiveCamera(40,1,.03,120),ortho=new THREE.OrthographicCamera(-9,9,6,-6,.01,100);let camera=perspective;
const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.maxPolarAngle=Math.PI/2.01;orbit.minDistance=1;orbit.maxDistance=45;orbit.target.set(7,0,4.5);orbit.screenSpacePanning=true;
scene.add(new THREE.HemisphereLight(0xf2f7ff,0x667478,2.8));const sun=new THREE.DirectionalLight(0xfff4e5,3.8);sun.position.set(1,14,6);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-12,right:12,top:12,bottom:-12,near:.1,far:40});sun.shadow.bias=-.0003;sun.shadow.normalBias=.025;sun.target.position.set(7,0,4);scene.add(sun,sun.target);const fill=new THREE.DirectionalLight(0xb9dfff,1.3);fill.position.set(13,7,-3);scene.add(fill);
const defs={architecture:['Архитектура','#dedfdb',true],doors:['Двери и окна','#92bdd0',true],furniture:['Мебель','#bd9365',true],plumbing:['Сантехника','#ecf0f1',true],heating:['Отопление / тёплый пол','#eeb65b',false],power:['Силовая сеть','#f27858',false],lighting:['Освещение','#f6d883',false],ftp:['FTP / Ethernet','#4eaaff',false],smart:['Smart Home','#57d5ba',false],curtains:['Приводы штор','#ba9afa',false],hvac:['Климат','#edb75e',false],sensors:['Датчики протечки','#50d3df',false],conduits:['Гофры','#96a8b4',false],boxes:['Распредкоробки','#b5c8d2',false],labels:['Подписи помещений','#ffffff',false]};
const groups={},routeGroups={};for(const [k,v]of Object.entries(defs)){groups[k]=new THREE.Group();groups[k].name=k;scene.add(groups[k]);groups[k].visible=v[2];const l=document.createElement('label');l.className='layer';l.innerHTML=`<span><i style="--c:${v[1]}"></i>${v[0]}</span><input type="checkbox" ${v[2]?'checked':''} aria-label="${v[0]}">`;l.querySelector('input').onchange=e=>{groups[k].visible=e.target.checked;defs[k][2]=e.target.checked;unselect();syncRoutes();};$('#layers').append(l);}
const nodeGroup=new THREE.Group(),blueGroup=new THREE.Group(),outlineGroup=new THREE.Group();scene.add(nodeGroup,blueGroup,outlineGroup);nodeGroup.visible=false;
let activeCircuit=null;let project,baseline,history,mode='view',view='3d',cut=true,blue=false,selected=null,beforeDrag=null,dragged=false;const objects=new Map(),wallMeshes=[];let blueprintMesh,toastTimer;
const materialCache=new Map();const mat=(color,extra={})=>{const key=JSON.stringify([color,extra]);if(!materialCache.has(key))materialCache.set(key,new THREE.MeshStandardMaterial({color,roughness:.78,...extra}));return materialCache.get(key);};const materials={wall:mat('#e2e0d9'),cap:mat('#bfd1d6'),floor:mat('#b6b1a4'),oak:mat('#a7835b'),fabric:mat('#aebcba'),linen:mat('#ebe7da'),dark:mat('#303c42'),white:mat('#eef0eb'),stone:mat('#bbc4c1'),glass:mat('#a8d2e0',{transparent:true,opacity:.3,depthWrite:false,metalness:.15}),metal:mat('#637783',{metalness:.65,roughness:.3})};
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function box(g,w,h,d,x,y,z,m,rounded=false){const mesh=new THREE.Mesh(rounded?new RoundedBoxGeometry(w,h,d,2,Math.min(.045,w/5,h/5,d/5)):new THREE.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);return mesh;}
function cylinder(g,r,h,x,y,z,m,segments=16){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,segments),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);return mesh;}
function polygon(g,pts,y,material,depth=0){const shape=new THREE.Shape(pts.map(p=>new THREE.Vector2(p[0],-p[1])));const geo=depth?new THREE.ExtrudeGeometry(shape,{depth,bevelEnabled:false}):new THREE.ShapeGeometry(shape);geo.rotateX(-Math.PI/2);const mesh=new THREE.Mesh(geo,material);mesh.position.y=y;mesh.receiveShadow=true;g.add(mesh);return mesh;}
function clear(g){for(const c of [...g.children]){g.remove(c);c.traverse(o=>{o.geometry?.dispose();if(o.userData.ownMaterial){o.material?.map?.dispose();o.material?.dispose();}});}}
function furniture(o){const g=new THREE.Group(),[w,h,d]=o.size,k=o.kind,b=(ww,hh,dd,x,y,z,m=materials.oak,r=false)=>box(g,ww,hh,dd,x,y,z,m,r);g.userData={id:o.id,record:o,kind:'object'};
 if(k==='panel'){
 b(w,h,.035,0,h/2,-d/2,materials.dark);for(const x of [-1,1])b(.025,h,d,x*w/2,h/2,0,materials.metal);b(w,.035,d,0,h,0,materials.metal);b(w,.035,d,0,0,0,materials.metal);
 const rails=o.id==='PANEL'?project.electrical?.panelLayout?.rails:null;
 if(rails){rails.forEach((row,i)=>{const y=h-.16-i*(h-.27)/8;b(w*.9,.018,.035,0,y,0,materials.metal);let x=-w*.45;for(const item of row){const width=w*.9*item.din/24;b(width-.004,.115,.07,x+width/2,y+.015,.065,mat(item.kind==='module'?'#28796f':item.kind==='reserve'?'#3b4a56':'#e0e5e1'));if(item.kind!=='reserve')b(Math.min(.028,width*.45),.037,.012,x+width/2,y+.015,.108,materials.dark);x+=width;}});}
 else for(let i=0;i<5;i++){b(w*.86,.09,.11,0,h-.2-i*.15,0,materials.dark);for(let j=0;j<8;j++)b(.03,.026,.01,-w*.35+j*w*.1,h-.2-i*.15,.06,mat('#4eaaff'));}
 }
 else if(k==='bed'){b(w,.2,d,0,.17,0);b(w-.04,.24,d-.04,0,.39,0,materials.linen,true);b(w,.85,.09,0,.52,-d/2,materials.fabric,true);b(w-.08,.035,d*.52,0,.53,d*.22,materials.fabric,true);for(const x of w>1.4?[-w*.25,w*.25]:[0])b(w>1.4?w*.4:w*.75,.13,.42,x,.56,-d*.33,materials.white,true);}
 else if(k==='sofa'){b(w,.24,d,0,.23,0,materials.oak,true);b(w,.56,.2,0,.6,-d*.43,materials.fabric,true);for(const x of [-1,1])b(.18,.55,d,x*(w/2-.09),.5,0,materials.fabric,true);for(let i=0;i<3;i++)b((w-.4)/3-.025,.22,d-.24,(i-1)*(w-.4)/3,.47,.08,materials.linen,true);}
 else if(k==='chair'){b(w,.12,d,0,.47,0,materials.fabric,true);b(w,.43,.09,0,.72,-d/2+.04,materials.fabric,true);for(const x of [-1,1])for(const z of [-1,1])b(.035,.45,.035,x*w*.36,.225,z*d*.36,materials.dark);}
 else if(k==='table'||k==='island'){b(w,.08,d,0,h-.04,0,k==='island'?materials.stone:materials.oak,true);if(k==='island')b(w-.1,h-.08,d-.12,0,(h-.08)/2,0,materials.oak);else for(const x of [-1,1])for(const z of [-1,1])b(.07,h-.08,.07,x*(w/2-.12),(h-.08)/2,z*(d/2-.12),materials.dark);}
 else if(k==='roundTable'){cylinder(g,w/2,.065,0,h-.03,0,materials.oak,28);cylinder(g,.075,h-.07,0,(h-.07)/2,0,materials.dark);}
 else if(['cabinet','fridge','oven','washer','piano'].includes(k)){b(w,h,d,0,h/2,0,materials.oak);const count=Math.max(1,Math.round(w/.6));for(let i=0;i<count;i++){const x=-w/2+w/count*(i+.5);b(w/count-.012,h-.04,.018,x,h/2,d/2+.01,k==='fridge'||k==='washer'?materials.white:materials.stone);b(.015,Math.min(.3,h*.25),.025,x+w/count*.3,h*.65,d/2+.04,materials.dark);}if(k==='washer'){const door=cylinder(g,.21,.03,0,h*.52,d/2+.04,materials.dark,24);door.rotation.x=Math.PI/2;}if(k==='oven')b(w*.78,.45,.04,0,h*.6,d/2+.04,materials.dark);if(k==='piano'){b(w,.04,.23,0,.76,d/2+.12,materials.white);for(let i=0;i<22;i++)b(.018,.02,.12,-w/2+.04+i*(w-.08)/22,.8,d/2+.09,materials.dark);}}
 else if(k==='sink'){b(w,.72,d,0,.36,0,materials.oak);b(w,.045,d,0,.75,0,materials.white,true);b(w*.7,.018,d*.65,0,.78,0,materials.dark,true);b(w*.6,.019,d*.55,0,.786,0,materials.white,true);b(.025,.23,.025,0,.85,-d*.3,materials.metal);b(.025,.025,.15,0,.96,-d*.2,materials.metal);}
 else if(k==='toilet'){b(w*.7,.32,d*.65,0,.22,.02,materials.white,true);b(w,.12,d*.8,0,.4,.06,materials.white,true);b(w*.85,.48,.12,0,.53,-d*.4,materials.white,true);b(w*.6,.012,d*.42,0,.466,.08,materials.dark,true);}
 else if(k==='shower'){b(w,.07,d,0,.035,0,materials.white,true);b(.025,2,d,-w/2,1,0,materials.glass);b(.025,.7,.025,w*.35,1.4,-d*.4,materials.metal);cylinder(g,.09,.02,w*.35,1.9,-d*.25,materials.metal);}
 else if(k==='convector'){b(w,h,d,0,h/2,0,materials.dark);for(let i=0;i<Math.floor(w/.08);i++)b(.015,.01,d-.01,-w/2+i*.08,h+.006,0,materials.metal);}
 else if(k==='curtain'){b(w,.065,.065,0,.04,0,materials.metal);b(.06,.25,.06,w/2,.0,0,materials.white);}
 else if(k==='radiator'){b(w,h,d,0,h/2,0,materials.white);for(let i=0;i<12;i++)b(.015,h,.015,-w/2+i*w/12,h/2,d/2+.01,materials.metal);}
 else if(k==='ac'){b(w,h,d,0,h/2,0,materials.white,true);b(w*.8,.035,.015,0,.06,d/2,materials.dark);}
 else if(k==='track'){b(w,h,d,0,0,0,materials.dark);for(let i=0;i<3;i++)cylinder(g,.035,.10,0,-.05,(i-1)*d*.36,materials.dark);}
 else if(k==='pendant'){cylinder(g,.008,.7,0,.35,0,materials.dark);cylinder(g,w/2,h,0,-h/2,0,materials.oak,24);cylinder(g,w*.42,.008,0,-h,0,materials.white);}
 else if(k==='light'){cylinder(g,w/2,h,0,0,0,materials.dark);cylinder(g,w*.4,.005,0,-h/2-.004,0,mat('#fff1c5',{emissive:'#fff1c5',emissiveIntensity:.6}));}
 else {const c=defs[o.layer]?.[1]||'#cbdce3';b(w,h,d,0,h/2,0,materials.white,true);b(w*.7,h*.6,.006,0,h*.53,d/2+.006,mat(c,{emissive:c,emissiveIntensity:.2}),true);if(k==='panel')for(let i=0;i<9;i++)b(.025,.05,.009,-w*.35+(i%3)*.14,h*.25+Math.floor(i/3)*.15,d/2+.014,materials.dark);}
 g.position.fromArray(o.position);g.rotation.fromArray([...o.rotation,'XYZ']);g.scale.fromArray(o.scale);return g;
}
function rebuildArchitecture(){clear(groups.architecture);clear(groups.doors);clear(nodeGroup);wallMeshes.length=0;
 polygon(groups.architecture,project.floorPolygon,-.14,materials.floor,.14);
 for(const r of project.rooms)polygon(groups.architecture,r.polygon,.004,['Санузел','Мастер-санузел','Тамбур','Прачечная','Техкомната'].includes(r.name)?materials.stone:materials.floor);
 for(const w of project.walls){const f=wallFrame(project,w),g=new THREE.Group();g.position.set(f.a[0],0,f.a[1]);g.rotation.y=-Math.atan2(f.dz,f.dx);groups.architecture.add(g);const height=blue?.07:cut?Math.min(+$('#wallheight').value,w.height):w.height;const segment=(a,b,lo,hi)=>{if(b-a<.001||hi-lo<.001)return;const mesh=box(g,b-a,hi-lo,w.thickness,(a+b)/2,(hi+lo)/2,0,blue?mat('#39a6d1'):materials.wall);mesh.userData.wallId=w.id;wallMeshes.push(mesh);if(!blue)box(g,b-a,.012,w.thickness+.003,(a+b)/2,hi+.003,0,materials.cap);};let at=0;
  for(const o of project.openings.filter(o=>o.wallId===w.id).sort((a,b)=>a.offset-b.offset)){segment(at,o.offset,0,height);segment(o.offset,o.offset+o.width,0,Math.min(o.sillHeight,height));segment(o.offset,o.offset+o.width,o.sillHeight+o.height,height);at=o.offset+o.width;
   const dg=new THREE.Group();dg.position.fromArray(openingPosition(project,o));dg.rotation.y=-Math.atan2(f.dz,f.dx);groups.doors.add(dg);const dh=Math.min(o.height,Math.max(.02,height-o.sillHeight));
   if(!blue&&height>o.sillHeight){if(o.type==='window'){box(dg,o.width,.035,.10,0,.015,0,materials.metal);box(dg,o.width,.035,.10,0,dh,0,materials.metal);for(const x of [-o.width/2,0,o.width/2])box(dg,.035,dh,.08,x,dh/2,0,materials.metal);box(dg,o.width,dh,.015,0,dh/2,0,materials.glass);}else{const pivot=new THREE.Group();pivot.position.x=(o.hingeAtEnd?1:-1)*o.width/2;pivot.rotation.y=o.hinge*Math.PI/2;dg.add(pivot);const side=o.hingeAtEnd?-1:1;box(pivot,o.width,dh,.035,side*o.width/2,dh/2,0,materials.oak);if(dh>.85)box(pivot,.1,.025,.07,side*(o.width-.12),.85,.03,materials.metal);}}
  }segment(at,f.length,0,height);
 }
 for(const n of project.nodes){const h=new THREE.Mesh(new THREE.SphereGeometry(.075,12,8),mat('#80daf4',{depthTest:false,emissive:'#80daf4',emissiveIntensity:.3}));h.position.set(n.position[0],.2,n.position[1]);h.renderOrder=99;h.userData={id:n.id,kind:'node',record:n};nodeGroup.add(h);}
 nodeGroup.visible=mode==='walls';
}
function roundedCurve(raw){const points=raw.map(p=>new THREE.Vector3(...p)).filter((p,i,a)=>!i||p.distanceTo(a[i-1])>.001);const path=new THREE.CurvePath();if(points.length<2)return null;let previous=points[0];for(let i=1;i<points.length-1;i++){const p=points[i],radius=Math.min(.12,p.distanceTo(points[i-1])*.25,p.distanceTo(points[i+1])*.25);const a=p.clone().add(points[i-1].clone().sub(p).normalize().multiplyScalar(radius)),b=p.clone().add(points[i+1].clone().sub(p).normalize().multiplyScalar(radius));path.add(new THREE.LineCurve3(previous,a));path.add(new THREE.QuadraticBezierCurve3(a,p,b));previous=b;}path.add(new THREE.LineCurve3(previous,points.at(-1)));return path;}
function buildRoutes(){for(const g of Object.values(routeGroups)){clear(g);scene.remove(g);}for(const k of Object.keys(routeGroups))delete routeGroups[k];clear(groups.conduits);clear(groups.boxes);let ribs=[];
 for(const b of project.junctionBoxes){const g=new THREE.Group();box(g,.18,.12,.18,0,0,0,materials.white,true);box(g,.15,.015,.15,0,.07,0,materials.metal);g.position.fromArray(b.position);g.userData={id:b.id,record:b,kind:'box'};groups.boxes.add(g);objects.set(b.id,g);}
 for(const r of project.routes){const curve=roundedCurve(r.route);if(!curve)continue;const g=routeGroups[r.type]||=new THREE.Group();if(!g.parent)scene.add(g);const geo=new THREE.TubeGeometry(curve,Math.min(100,Math.max(8,Math.ceil(curve.getLength()*8))),.006,6,false);const tube=new THREE.Mesh(geo,mat(defs[r.type]?.[1]||'#aabac5'));tube.userData={id:r.id,record:r,kind:'route'};g.add(tube);objects.set(r.id,tube);const sleeve=new THREE.Mesh(new THREE.TubeGeometry(curve,Math.min(80,Math.max(8,Math.ceil(curve.getLength()*6))),.012,6,false),mat('#94a8b5',{transparent:true,opacity:.28,depthWrite:false}));sleeve.userData.circuit=r.circuit;groups.conduits.add(sleeve);
  if(r.homeRun){for(let i=0,n=Math.min(45,Math.ceil(curve.getLength()/.20));i<=n;i++){ribs.push({p:curve.getPoint(i/n),t:curve.getTangent(i/n)});}}
 }
 if(ribs.length){const geom=new THREE.TorusGeometry(.013,.002,3,6),mesh=new THREE.InstancedMesh(geom,materials.metal,ribs.length),d=new THREE.Object3D();ribs.forEach((r,i)=>{d.position.copy(r.p);d.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),r.t);d.updateMatrix();mesh.setMatrixAt(i,d.matrix);});mesh.userData.ribs=true;groups.conduits.add(mesh);}syncRoutes();
}
function syncRoutes(){for(const [k,g]of Object.entries(routeGroups))g.visible=defs[k]?.[2]&&!blue;groups.conduits.visible=defs.conduits[2]&&!blue;
 for(const g of Object.values(routeGroups))for(const o of g.children)o.visible=!activeCircuit||o.userData.record.circuit===activeCircuit;
 for(const o of groups.conduits.children)o.visible=!activeCircuit||(!o.userData.ribs&&o.userData.circuit===activeCircuit);
 for(const o of groups.boxes.children)o.visible=!activeCircuit||o.userData.record.circuit===activeCircuit;
 }
function labels(){clear(groups.labels);for(const r of project.rooms){const pts=r.polygon,x=pts.reduce((s,p)=>s+p[0],0)/pts.length,z=pts.reduce((s,p)=>s+p[1],0)/pts.length;const cv=document.createElement('canvas');cv.width=512;cv.height=100;const c=cv.getContext('2d');c.fillStyle='#10212ade';c.fillRect(0,0,512,100);c.fillStyle='#edf3f5';c.textAlign='center';c.font='28px system-ui';c.fillText(r.name,256,43);c.fillStyle='#b7ccd5';c.font='23px system-ui';c.fillText(r.areaSource.toFixed(2)+' м²',256,78);const tx=new THREE.CanvasTexture(cv),sp=new THREE.Sprite(new THREE.SpriteMaterial({map:tx,depthTest:false}));sp.userData.ownMaterial=true;sp.position.set(x,.25,z);sp.scale.set(1.6,.313,1);groups.labels.add(sp);}}
function rebuild(){unselect();objects.clear();rebuildArchitecture();for(const [k,g]of Object.entries(groups))if(!['architecture','doors','labels','conduits','boxes'].includes(k))clear(g);for(const o of project.objects){const g=furniture(o);(groups[o.layer]||groups.furniture).add(g);objects.set(o.id,g);}for(const z of project.heatingZones)polygon(groups.heating,z.polygon,.025,mat('#f3bc5d',{transparent:true,opacity:.45,depthWrite:false}));buildRoutes();labels();applyVisibility();updateStats();electricalPanel.render();}
function applyVisibility(){for(const [k,g]of Object.entries(groups))g.visible=defs[k][2]&&(!blue||k==='architecture');syncRoutes();blueGroup.visible=blue;outlineGroup.visible=blue;}
const textures=new Map();async function setBlueprint(){const s=project.sources.find(s=>s.id===$('#source').value)||project.sources[0];if(!textures.has(s.image))textures.set(s.image,new THREE.TextureLoader().loadAsync(s.image));try{const tx=await textures.get(s.image);tx.colorSpace=THREE.SRGBColorSpace;clear(blueGroup);const m=new THREE.MeshBasicMaterial({map:tx,transparent:true,opacity:+$('#opacity').value/100,depthWrite:false});blueprintMesh=new THREE.Mesh(new THREE.PlaneGeometry(...s.size),m);blueprintMesh.rotation.x=-Math.PI/2;blueprintMesh.position.set(s.origin[0]+s.size[0]/2,.02,s.origin[1]+s.size[1]/2);blueGroup.add(blueprintMesh);}catch(e){toast('Не удалось загрузить чертёж');}}
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);perspective.aspect=w/h;perspective.updateProjectionMatrix();const aspect=w/h,span=Math.max(10,16/aspect);ortho.left=-span*aspect/2;ortho.right=span*aspect/2;ortho.top=span/2;ortho.bottom=-span/2;ortho.updateProjectionMatrix();}addEventListener('resize',resize);
function setView(v){if(fallback)v='top';view=v;camera=v==='top'?ortho:perspective;orbit.object=camera;transform.camera=camera;orbit.enableRotate=v!=='top';orbit.target.set(7.1,0,4.5);if(v==='top'){camera.position.set(7.1,25,4.5);camera.up.set(0,0,-1);camera.zoom=1;}else{camera.up.set(0,1,0);const distance=host.clientWidth<600?1.45:1;if(v==='walk'){camera.position.set(11.5,1.65,7.5);orbit.target.set(7,1.35,5.8);cut=false;}else camera.position.set(7.1+12*distance,15*distance,4.5+15*distance);}resize();orbit.update();$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#viewtitle').textContent=v==='top'?'План и размеры':v==='walk'?'Внутри дома':'Пространство целиком';$('#cut').classList.toggle('active',cut);if(project)rebuildArchitecture();}
function toggleBlue(value){blue=value;$('#blueprint').classList.toggle('active',blue);if(blue){setView('top');setBlueprint();}rebuildArchitecture();applyVisibility();}
const transform=new TransformControls(camera,renderer.domElement);transform.setSize(innerWidth<900?1.3:1);transform.setTranslationSnap(.05);transform.setRotationSnap(Math.PI/12);scene.add(transform.getHelper());
const selectionBox=new THREE.BoxHelper(new THREE.Object3D(),0x69d9f7);selectionBox.visible=false;selectionBox.material.depthTest=false;selectionBox.renderOrder=100;scene.add(selectionBox);
function unselect(){transform.detach();selectionBox.visible=false;selected=null;$('#coordinates').hidden=true;$('#selection').replaceChildren();const b=document.createElement('b');b.textContent=mode==='walls'?'Выберите узел стены':'Выберите объект';$('#selection').append(b);}
function showSelection(){if(!selected)return;const o=selected.userData.record,kind=selected.userData.kind;$('#selection').replaceChildren();for(const [tag,t]of [['b',o.name||o.id],['p',o.id],['p',o.status==='pdf_vector'?'Из векторного чертежа':o.status==='pdf_scaled'?'Перенесено из инженерного плана':'Требует проверки'],['code',o.source||'Проектное предложение']]){const el=document.createElement(tag);el.textContent=t;$('#selection').append(el);}if(kind==='box'){const el=document.createElement('p');el.textContent='Линии: '+project.routes.filter(r=>r.from===o.id||r.to===o.id).map(r=>r.id).join(', ');$('#selection').append(el);}if(kind==='route'){const el=document.createElement('p');el.textContent=`${o.from} → ${o.to} · ${o.cable} · ${o.conduit}`;$('#selection').append(el);}
 const movable=['object','box','node'].includes(kind)&&mode!=='view';$('#coordinates').hidden=!movable;$('#delete').disabled=kind==='node'||o.kind==='panel';if(movable){$('#posx').value=selected.position.x.toFixed(3);$('#posz').value=selected.position.z.toFixed(3);$('#posy').value=selected.position.y.toFixed(3);$('#posy').disabled=kind==='node';}
 if(o.circuit){const c=project.electrical?.circuits.find(c=>c.id===o.circuit);if(c){const el=document.createElement('p');el.textContent=`${c.id} · ${c.cable} · ${c.channel||c.protection}`;$('#selection').append(el);}}
 if(kind==='object'||kind==='box'){const p=selected.position;let dist=Infinity;for(const w of project.walls){const f=wallFrame(project,w),t=Math.max(0,Math.min(f.length,(p.x-f.a[0])*f.dx+(p.z-f.a[1])*f.dz));dist=Math.min(dist,Math.hypot(p.x-f.a[0]-f.dx*t,p.z-f.a[1]-f.dz*t)-w.thickness/2);}const el=document.createElement('p');el.textContent='От центра до стены: '+Math.round(Math.max(0,dist)*1000)+' мм';$('#selection').append(el);}
}
function select(o){selected=o;showSelection();if(o.userData.kind!=='node'){selectionBox.setFromObject(o);selectionBox.visible=true;}if(!fallback&&mode!=='view'&&o.userData.kind!=='route'){transform.attach(o);if(mode==='walls'){transform.setMode('translate');transform.showY=false;transform.showX=transform.showZ=true;}else{transform.showY=true;}}}
function setMode(m){mode=mode===m?'view':m;unselect();nodeGroup.visible=mode==='walls';if(mode==='walls'){toggleBlue(true);$('#hint').textContent='Двигайте синие узлы · связанные стены перестраиваются';}else $('#hint').textContent='Коснитесь объекта · двигайте стрелками или задайте координаты';$('#editobjects').classList.toggle('active',mode==='objects');$('#editwalls').classList.toggle('active',mode==='walls');orbit.enabled=true;}
function syncRecord(){if(!selected)return;const o=selected.userData.record;if(selected.userData.kind==='node'){o.position=[selected.position.x,selected.position.z];project.verification=Array.from(new Set([...project.verification,'Планировка изменена вручную. Сверьте полы, мебель, инженерные точки и трассы с новой геометрией.']));}else{o.position=selected.position.toArray();o.rotation=[selected.rotation.x,selected.rotation.y,selected.rotation.z];o.scale=selected.scale.toArray();o.status='needs_verification';reroute(project,o.id);}showSelection();if(selectionBox.visible)selectionBox.setFromObject(selected);}
function persist(){try{localStorage.setItem('vydrino-v8.2',JSON.stringify(project));}catch(e){toast('Автосохранение недоступно — экспортируйте JSON');}}
function changed(){history.push(project);persist();updateStats();$('#undo').disabled=history.index===0;$('#redo').disabled=history.index===history.entries.length-1;}
transform.addEventListener('dragging-changed',e=>{orbit.enabled=!e.value;if(e.value){beforeDrag=clone(project);dragged=true;}else{try{syncRecord();validate(project);changed();const id=selected?.userData.id,kind=selected?.userData.kind;rebuild();const obj=kind==='node'?nodeGroup.children.find(n=>n.userData.id===id):objects.get(id);if(obj)select(obj);}catch(err){project=beforeDrag;rebuild();toast(err.message);}setTimeout(()=>dragged=false,50);}});
transform.addEventListener('objectChange',()=>{if(selected){selectionBox.setFromObject(selected);$('#posx').value=selected.position.x.toFixed(3);$('#posz').value=selected.position.z.toFixed(3);$('#posy').value=selected.position.y.toFixed(3);}});
const ray=new THREE.Raycaster();let down=null;renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>5||dragged||transform.dragging)return;const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const candidates=mode==='walls'?nodeGroup.children:[...objects.values()].filter(o=>{let p=o;while(p){if(!p.visible)return false;p=p.parent;}return true;});const hit=ray.intersectObjects(candidates,true)[0];let o=hit?.object;while(o&&!o.userData.id)o=o.parent;if(o){select(o);if(mode==='view'){showTab('edit');$('#side').classList.add('open');}}else unselect();down=null;});
function updateStats(){$('#stats').innerHTML=`<span><b>${project.rooms.length}</b>помещений</span><span><b>${project.walls.length}</b>стен</span><span><b>${project.openings.length}</b>проёмов</span>`;$('#rooms').replaceChildren();for(const r of project.rooms){const p=document.createElement('p');p.textContent=r.name+' · '+r.areaSource.toFixed(2)+' м²';$('#rooms').append(p);}$('#issues').replaceChildren();for(const t of project.verification){const p=document.createElement('p');p.textContent=t;$('#issues').append(p);}}
const electricalPanel=electricalUI($('[data-panel=electrical]'),()=>project,showCircuit,focusPanel);
function electricalLayers(){for(const k of ['power','lighting','smart','ftp','sensors','curtains','hvac','boxes'])defs[k][2]=true;defs.furniture[2]=false;defs.labels[2]=true;for(const [i,k]of Object.keys(defs).entries())$('#layers').children[i].querySelector('input').checked=defs[k][2];}
function showCircuit(c){activeCircuit=c?.id||null;if(blue)toggleBlue(false);electricalLayers();applyVisibility();unselect();if(c){const o=objects.get(c.consumers[0]);if(o)select(o);}$('#viewtitle').textContent=c?c.id+' · '+c.name:'Электрика · все трассы';}
function focusPanel(){activeCircuit=null;if(blue)toggleBlue(false);electricalLayers();applyVisibility();setView(fallback?'top':'3d');const o=objects.get('PANEL');if(o){select(o);orbit.target.set(.4,1.4,2.5);if(fallback){camera.position.set(.4,25,2.5);camera.zoom=2;}else camera.position.set(3.6,2.6,4.1);camera.updateProjectionMatrix();orbit.update();}$('#viewtitle').textContent='ЩР-01 · техкомната';}
$('#electrical').onclick=()=>{showCircuit(null);showTab('electrical');$('#side').classList.add('open');$('#menu').setAttribute('aria-expanded','true');};
function showTab(t){$$('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==t);$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));}
function exportJSON(){validate(project);const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}));a.href=url;a.download='vydrino-project-v8.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);persist();toast('JSON подготовлен для сохранения');}
$$('[data-view]').forEach(b=>b.onclick=()=>{if(b.dataset.view!=='top'&&blue)toggleBlue(false);setView(b.dataset.view);});$$('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$('#menu').onclick=()=>{const open=$('#side').classList.toggle('open');$('#menu').setAttribute('aria-expanded',open);};$('#closepanel').onclick=()=>{$('#side').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');};$('#home').onclick=()=>setView(view);$('#cut').onclick=()=>{cut=!cut;$('#cut').classList.toggle('active',cut);rebuildArchitecture();};$('#wallheight').oninput=()=>{$('#heightout').textContent=(+$('#wallheight').value).toFixed(2)+' м';cut=true;$('#cut').classList.add('active');rebuildArchitecture();};$('#blueprint').onclick=()=>toggleBlue(!blue);$('#source').onchange=setBlueprint;$('#opacity').oninput=()=>{$('#opacityout').textContent=$('#opacity').value+'%';if(blueprintMesh)blueprintMesh.material.opacity=+$('#opacity').value/100;};$('#editobjects').onclick=()=>{if(blue)toggleBlue(false);setMode('objects');};$('#editwalls').onclick=()=>setMode('walls');
$$('[data-mode]').forEach(b=>b.onclick=()=>{if(mode==='walls'&&b.dataset.mode!=='translate'){toast('Узлы стен можно только перемещать');return;}transform.setMode(b.dataset.mode);transform.showX=transform.showZ=b.dataset.mode!=='rotate';transform.showY=mode!=='walls';$$('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));});$('#snap').onchange=()=>transform.setTranslationSnap(+$('#snap').value||null);
$('#applypos').onclick=()=>{if(!selected)return;const old=clone(project);selected.position.set(+$('#posx').value,selected.userData.kind==='node'?.2:+$('#posy').value,+$('#posz').value);try{syncRecord();validate(project);changed();rebuild();}catch(e){project=old;rebuild();toast(e.message);}};
$('#delete').onclick=()=>{if(!selected||selected.userData.kind==='node'||selected.userData.record.kind==='panel')return;removeObject(project,selected.userData.id);changed();rebuild();};$('#undo').onclick=()=>{const p=history.undo();if(p){project=p;rebuild();persist();$('#undo').disabled=history.index===0;$('#redo').disabled=false;}};$('#redo').onclick=()=>{const p=history.redo();if(p){project=p;rebuild();persist();$('#redo').disabled=history.index===history.entries.length-1;$('#undo').disabled=false;}};$('#export').onclick=$('#save').onclick=exportJSON;$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>10000000)throw Error('JSON слишком большой');const p=JSON.parse(await f.text());validate(p);project=p;changed();rebuild();await setBlueprint();toast('Проект импортирован');}catch(err){toast('Импорт отменён: '+err.message);}e.target.value='';};$('#reset').onclick=()=>{if(confirm('Вернуть исходную модель? Текущие правки можно предварительно экспортировать в JSON.')){project=clone(baseline);changed();rebuild();}};
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();(e.shiftKey?$('#redo'):$('#undo')).click();}if(e.key==='Escape'){mode='view';unselect();nodeGroup.visible=false;orbit.enabled=true;}});
try{const response=await fetch('project.json?v=8.2.1');if(!response.ok)throw Error('Не удалось загрузить проект');baseline=await response.json();validate(baseline);project=clone(baseline);try{const saved=JSON.parse(localStorage.getItem('vydrino-v8.2'));if(saved){validate(saved);project=saved;}}catch(e){}history=new History(project);if((()=>{try{return localStorage.getItem('vydrino-v8')&&!localStorage.getItem('vydrino-v8.2')}catch{return false}})()){const old=document.createElement('button');old.className='wide';old.textContent='Скачать прежние правки v8';old.onclick=()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([localStorage.getItem('vydrino-v8')],{type:'application/json'}));a.href=u;a.download='vydrino-previous-edits-v8.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};$('[data-panel=project]').prepend(old);toast('Новая электрика загружена. Прежние правки доступны во вкладке «Проект».');} for(const s of project.sources){const op=document.createElement('option');op.value=s.id;op.textContent=s.name;$('#source').append(op);}rebuild();setView('3d');$('#loading').hidden=true;if(fallback){$('#hint').textContent='2D-режим: WebGL недоступен · правки через координаты';$$('[data-view]').filter(b=>b.dataset.view!=='top').forEach(b=>b.disabled=true);}renderer.setAnimationLoop(()=>{orbit.update();renderer.render(scene,camera);});}catch(e){$('#loading').textContent='Ошибка загрузки: '+e.message;console.error(e);}
