import * as THREE from 'three';
import {wallFrame} from './model.js?v=8.4.0';
export function walkController(host,canvas,camera,getProject){
 let enabled=false,yaw=0,pitch=0,look=null,stick=null,moveX=0,moveY=0;const keys=new Set();
 const pad=document.createElement('div');pad.className='walk-pad';pad.hidden=true;pad.setAttribute('aria-label','Джойстик перемещения');const thumb=document.createElement('span');pad.append(thumb);const help=document.createElement('div');help.className='walk-help';help.hidden=true;help.textContent='Джойстик / WASD — идти · потяните экран — осмотреться';host.append(pad,help);
 const reset=()=>{keys.clear();moveX=moveY=0;thumb.style.transform='translate(0,0)';};
 pad.onpointerdown=e=>{stick=e.pointerId;pad.setPointerCapture(stick);e.stopPropagation();};pad.onpointermove=e=>{if(e.pointerId!==stick)return;const r=pad.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,len=Math.max(34,Math.hypot(dx,dy));moveX=dx/len;moveY=-dy/len;thumb.style.transform=`translate(${moveX*34}px,${-moveY*34}px)`;};pad.onpointerup=pad.onpointercancel=()=>{stick=null;reset();};
 canvas.addEventListener('pointerdown',e=>{if(enabled){look={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointermove',e=>{if(!enabled||look?.id!==e.pointerId)return;yaw-=(e.clientX-look.x)*.004;pitch=Math.max(-1.35,Math.min(1.35,pitch-(e.clientY-look.y)*.004));look.x=e.clientX;look.y=e.clientY;});canvas.addEventListener('pointerup',()=>look=null);canvas.addEventListener('pointercancel',()=>look=null);
 addEventListener('keydown',e=>{if(enabled&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)&&['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){keys.add(e.code);e.preventDefault();}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',reset);document.addEventListener('visibilitychange',reset);
 function inside(x,z,poly){let yes=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>z)!==(b[1]>z)&&x<(b[0]-a[0])*(z-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;}
 function free(x,z){const p=getProject();if(!inside(x,z,p.floorPolygon))return false;for(const w of p.walls){const f=wallFrame(p,w),t=(x-f.a[0])*f.dx+(z-f.a[1])*f.dz;if(t<-.18||t>f.length+.18)continue;const distance=Math.abs((x-f.a[0])*f.dz-(z-f.a[1])*f.dx);if(distance<w.thickness/2+.16){if(!p.openings.some(o=>o.wallId===w.id&&o.type==='door'&&t>o.offset+.16&&t<o.offset+o.width-.16))return false;}}
 for(const o of p.objects.filter(o=>['cabinet','bed','sofa','island','fridge','freezer','ovenTower','coffeeTower','dishwasher','hob','kitchenSink','dryingCabinet','washer'].includes(o.kind))){const dx=x-o.position[0],dz=z-o.position[2],a=o.rotation[1],lx=Math.cos(a)*dx-Math.sin(a)*dz,lz=Math.sin(a)*dx+Math.cos(a)*dz;if(Math.abs(lx)<o.size[0]*o.scale[0]/2+.12&&Math.abs(lz)<o.size[2]*o.scale[2]/2+.12)return false;}return true;}
 return {set(value){enabled=value;pad.hidden=help.hidden=!value;reset();if(value){yaw=0;pitch=0;camera.position.set(10.7,1.65,5.3);}},tick(dt){if(!enabled)return;const x=moveX+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),z=moveY+(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0),norm=Math.max(1,Math.hypot(x,z)),distance=Math.min(dt,.04)*1.5;const dx=(Math.cos(yaw)*x-Math.sin(yaw)*z)/norm*distance,dz=(-Math.sin(yaw)*x-Math.cos(yaw)*z)/norm*distance;if(free(camera.position.x+dx,camera.position.z))camera.position.x+=dx;if(free(camera.position.x,camera.position.z+dz))camera.position.z+=dz;camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0);camera.position.y=1.65;},free};
}
